### ISSUE TITLE
stompjs Angular sample with TLS support

### ISSUE THREAD

**Issue by msbasanth** [stomp-js/ng2-stompjs#147]
Hi,

Your sample is really helpful and I could connect this sample to our existing RabbitMQ server with ws://localhost:15674/ws.

I wanted to connect to RabbitMQ server securely. I enabled TLS in server by making necessary changes in rabbitmq.conf file (attached).
Could you please share what changes I should make so that I can connect to server using secure WebSocket. i.e. wss://localhost:15673/ws

[rabbitmq.conf.txt](https://github.com/stomp-js/ng2-stompjs-angular7/files/3161835/rabbitmq.conf.txt)

Regards
Basanth

**Comment by kum-deepak** [comment]
If you are using valid SSL certificates, there should be no additional settings needed.

Please type https://localhost:15673/ws in your browser bar and see that you are not getting any certificate errors. In Firefox (not tested recently though), you can permanently confirm the security exception. After that in that browser you should be able to connect using wss:.

To use with wss: you need a valid certificate (not self signed), otherwise, your end users will not be able to connect.

**Comment by msbasanth** [comment]
Is there any test certificate for trying out this scenario ?
Or Can you suggest some valid  certificate generation steps?

**Comment by msbasanth** [comment]
We could get the rabbitmq TLS connection with Firefox, followed  https://localhost:15673/ws and permanently confirmed the security exception. Now WebSocket connection wss://127.0.0.1:15673/ws is successful.
![RabbitMQ](https://user-images.githubusercontent.com/17777813/57683755-fbc60d00-7651-11e9-8657-4e01465b2a9a.gif)

In Chrome (Version 74.0.3729.131) not able to proceed due to certificate error.
We have my certificates added to trusted certificate root authority (mmc). Even with this why we have SEC_ERROR_UNKNOWN_ISSUER error? 

Regards
Basanth

**Comment by kum-deepak** [comment]
I do not know of any way to using WebSockets with an invalid certificate in Chrome. I can suggest for you to get a valid certificate.

**Comment by msbasanth** [comment]
Ok thanks I will get a valid certificate and then try.

Regards
Basanth
