### ISSUE TITLE
Connect to stomp broker with ng2-stompjs

### ISSUE THREAD

**Issue by theunreal** [stomp-js/ng2-stompjs#17]
I have the following pure javascript code where I can connect successfully to my spring boot with stomp using websocket in the same port:

```
function connect() {
    var socket = new SockJS('/gs-guide-websocket');
    stompClient = Stomp.over(socket);
    stompClient.connect({}, function (frame) {
        setConnected(true);
        console.log('Connected: ' + frame);
        stompClient.subscribe('/topic/greetings', function (greeting) {
            showGreeting(JSON.parse(greeting.body).content);
        });
    });
}
```

The problem is that I'm trying to connect using a new Angular 4 app, and can't figure out how to switch the example above to work with **ng2-stompjs**.

I tried to configure it as the following:

```
const stompConfig: StompConfig = {
      // Which server?
      url: 'ws://127.0.0.1:8080/gs-guide-websocket',
      // Headers
      // Typical keys: login, passcode, host
      headers: {
      },
      // How often to heartbeat?
      // Interval in milliseconds, set to 0 to disable
      heartbeat_in: 0, // Typical value 0 - disabled
      heartbeat_out: 20000, // Typical value 20000 - every 20 seconds
      // Wait in milliseconds before attempting auto reconnect
      // Set to 0 to disable
      // Typical value 5000 (5 seconds)
      reconnect_delay: 5000,
      // Will log diagnostics on console
      debug: true
    };
```

but I get:

```
stomp.service.ts:271 Thu Jul 20 2017 13:20:12 GMT+0300  "Whoops! Lost connection to ws://127.0.0.1:8080/gs-guide-websocket"
stomp.service.ts:271 Thu Jul 20 2017 13:20:12 GMT+0300  "Error: Whoops! Lost connection to ws://127.0.0.1:8080/gs-guide-websocket"
stomp.service.ts:271 Thu Jul 20 2017 13:20:12 GMT+0300"STOMP: scheduling reconnection in 5000ms"
```

Any idea what's wrong with my configuration? Why the pure javascript code works and I'm unable to connect with my Angular 4 app using this library?

**Comment by kum-deepak** [comment]
Most likely issue is caused because SockJS is not WebSocket, SockJS is WebSocket emulation. See https://github.com/sockjs/sockjs-client for a longer explanation.

I see following options:

- Some people have reported successfully using this library with Spring over WebSockets. Switch to use WebSockets (the endpoint will change). You will need to consult the server documentation to figure out the correct value. (Preferred)
- Configure this library to use SockJS, see: https://github.com/stomp-js/ng2-stompjs/blob/master/SockJS.md

Let me know if the above helps.

_On other note, if you need to use pure JS to connect, please see https://stomp-js.github.io/stomp-websocket/codo/extra/docs-src/sockjs.md.html to update the code (your JS sample) for automatic reconnect._

**Comment by theunreal** [comment]
Thanks @kum-deepak, 2nd option did the trick. it's working now.
