### ISSUE TITLE
Reconnection timeout and subscriptions

### ISSUE THREAD

**Issue by nohanna** [stomp-js/ng2-stompjs#75]
Hello,

I found a couple of issues for my case and don't know if there is a solution that I missed.

Actually, when I lost my connection, I found that it's not reconnecting with a timeout but with a delay. In my case, I need something like a timeout so it tries to reconnect every 5 seconds for example.

Furthermore, let's say that I've subscribed at 2 topics when I connect. I move on another page of my application and subscribed at 2 more topics. When I leave this page, I unsubscribe these 2 last topics. So I'm still subscribed at 2 topics. I re-move on this page, so subscribed again, and re-leave this page.
So I should be subscribed at 2 topics. But when I disconnect my websockets and reconnect, it subscribes at all the topics I subscribed when I was connected no matter how many times I subscribed/unsubscribed these topics. 
So in this example, when I reconnect, I will be subscribed at 6 topics instead of 2.

Sorry if my example is not really clear, I tried to explain as detailed as I can !

**Comment by kum-deepak** [comment]
Please create a simple application and share on GitHub for me to look. Many thanks!

**Comment by nohanna** [comment]
Ok I will do it as soon as I can.

Thanks for the fast answer !

**Comment by nohanna** [comment]
Here is my demo https://github.com/nohanna/stomp-demo, it's really basic.

It uses spring boot (with SockJS) / angular. The main isssue here is when I subscribe/unsubscribe and then disconnect, after the reconnection every subscribes are re-subscribed even the ones I unsubscribed before the disconnection. I put many console logs in my code to show you.

Sometimes reconnection doesn't work, I guess it's due to SockJS.
Another issue I found in this demo, maybe because it's too basic and I wrote it too fast, is that when you kill the MainApplication process, a lot of "/info" requests are sent, then when I restart it, the reconnection can't be done. But again, it might be my code !

Hope it helps.

**Comment by kum-deepak** [comment]
Thanks for sharing the code. I can suggest the following:

https://github.com/nohanna/stomp-demo/blob/master/testFront/src/app/components/my-page/my-page.component.ts#L25 (similarly in other components) - the stomp `subscribe` watches the connection state and resubscribes (https://stomp-js.github.io/ng2-stompjs/injectables/StompRService.html#subscribe), so you need not watch the `connected` state and resubscribe. Your code should look like the following:

```typescript
  constructor(private stompService: StompService) {
    this.subscriptions.push(
      this.stompService.stompSubscribe('/api/topic/topic1').subscribe((data: string) => this.updateTopic1(data))
    );
    this.subscriptions.push(
      this.stompService.stompSubscribe('/api/topic/topic2').subscribe((data: string) => this.updateTopic2(data))
    );
  }
```

In order for STOMP re-connection to work correctly, at https://github.com/nohanna/stomp-demo/blob/master/testFront/src/app/services/stomp.service.ts#L66 change to following (see https://stomp-js.github.io/ng2-stompjs/additional-documentation/sock-js.html):

```typescript
      url: () => new SockJS('/ws-test'),
``` 

Optionally, you can update your Spring Boot code to remove `.withSockJS();` so that it works as standard WebSocket. Standard WebSocket is recommended over SockJS.

In addition, once you make the above changes, some code in https://github.com/nohanna/stomp-demo/blob/master/testFront/src/app/services/stomp.service.ts is likely to become redundant.

**I have not actually run this code, my suggestions are based on reading your code.** Let me know if I need to submit these changes as a pull request into your repository.

**Comment by nohanna** [comment]
Ok I will try with those changes and get back to you.

Thanks for your answer.

**Comment by kum-deepak** [comment]
Great to hear that it has started working 😄 

As per STOMP standard the payload has no known types. Now a days typically JSON Is used, however that is a convention used by application. So, you will have to parse incoming messages yourself.

**Comment by nohanna** [comment]
Ok, it's fine, it finally works as expected :)
Thanks for your time !
